baseURL = 'https://cv.aws10.dominioshm.cat/'
languageCode = 'en-us'
title = 'Sergio Herruzo'

[params]
    subtitle = "Estudiante de Administraci√≥n de Sistemas"
    email = '2223_sergio.herruzo@iticbcn.cat'
    name = 'Sergio Herruzo'
